services:
  bot:
    image: salaries-aggregation
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db

  redis:
    image: redis:6.2-alpine
    hostname: redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - "6379:6379"

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
